// automatically generated by the FlatBuffers compiler, do not modify

package Filter.UIManagerMsg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AISObject extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AISObject __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long mmsi() { return (long)bb.getInt(bb_pos + 0) & 0xFFFFFFFFL; }
  public double lat() { return bb.getDouble(bb_pos + 8); }
  public double lon() { return bb.getDouble(bb_pos + 16); }
  public float cog() { return bb.getFloat(bb_pos + 24); }
  public float sog() { return bb.getFloat(bb_pos + 28); }

  public static int createAISObject(FlatBufferBuilder builder, long mmsi, double lat, double lon, float cog, float sog) {
    builder.prep(8, 32);
    builder.putFloat(sog);
    builder.putFloat(cog);
    builder.putDouble(lon);
    builder.putDouble(lat);
    builder.pad(4);
    builder.putInt((int)mmsi);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AISObject get(int j) { return get(new AISObject(), j); }
    public AISObject get(AISObject obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

