// automatically generated by the FlatBuffers compiler, do not modify

package Filter.UIManagerMsg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Attitude extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Attitude __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float roll() { return bb.getFloat(bb_pos + 0); }
  public float pitch() { return bb.getFloat(bb_pos + 4); }
  public float yaw() { return bb.getFloat(bb_pos + 8); }

  public static int createAttitude(FlatBufferBuilder builder, float roll, float pitch, float yaw) {
    builder.prep(4, 12);
    builder.putFloat(yaw);
    builder.putFloat(pitch);
    builder.putFloat(roll);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Attitude get(int j) { return get(new Attitude(), j); }
    public Attitude get(Attitude obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

