// automatically generated by the FlatBuffers compiler, do not modify

package Filter.UIManagerMsg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Map extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Map __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long range() { return (long)bb.getInt(bb_pos + 0) & 0xFFFFFFFFL; }
  public boolean follow() { return 0!=bb.get(bb_pos + 4); }
  public Filter.UIManagerMsg.Position center() { return center(new Filter.UIManagerMsg.Position()); }
  public Filter.UIManagerMsg.Position center(Filter.UIManagerMsg.Position obj) { return obj.__assign(bb_pos + 8, bb); }

  public static int createMap(FlatBufferBuilder builder, long range, boolean follow, double center_lat, double center_lon, double center_alt) {
    builder.prep(8, 32);
    builder.prep(8, 24);
    builder.putDouble(center_alt);
    builder.putDouble(center_lon);
    builder.putDouble(center_lat);
    builder.pad(3);
    builder.putBoolean(follow);
    builder.putInt((int)range);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Map get(int j) { return get(new Map(), j); }
    public Map get(Map obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

