// automatically generated by the FlatBuffers compiler, do not modify

package Filter.UIManagerMsg;

import com.example.yhmtmt.aws2.Radar;
import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class UIManagerMsg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static UIManagerMsg getRootAsUIManagerMsg(ByteBuffer _bb) { return getRootAsUIManagerMsg(_bb, new UIManagerMsg()); }
  public static UIManagerMsg getRootAsUIManagerMsg(ByteBuffer _bb, UIManagerMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UIManagerMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long t() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public Filter.UIManagerMsg.Control control() { return control(new Filter.UIManagerMsg.Control()); }
  public Filter.UIManagerMsg.Control control(Filter.UIManagerMsg.Control obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Position position() { return position(new Filter.UIManagerMsg.Position()); }
  public Filter.UIManagerMsg.Position position(Filter.UIManagerMsg.Position obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Velocity velocity() { return velocity(new Filter.UIManagerMsg.Velocity()); }
  public Filter.UIManagerMsg.Velocity velocity(Filter.UIManagerMsg.Velocity obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Attitude attitude() { return attitude(new Filter.UIManagerMsg.Attitude()); }
  public Filter.UIManagerMsg.Attitude attitude(Filter.UIManagerMsg.Attitude obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Engine engine() { return engine(new Filter.UIManagerMsg.Engine()); }
  public Filter.UIManagerMsg.Engine engine(Filter.UIManagerMsg.Engine obj) { int o = __offset(14); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public float depth() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public Filter.UIManagerMsg.Weather weather() { return weather(new Filter.UIManagerMsg.Weather()); }
  public Filter.UIManagerMsg.Weather weather(Filter.UIManagerMsg.Weather obj) { int o = __offset(18); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Map map() { return map(new Filter.UIManagerMsg.Map()); }
  public Filter.UIManagerMsg.Map map(Filter.UIManagerMsg.Map obj) { int o = __offset(20); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Radar radar() { return radar(new Radar()); }
  public Radar radar(Radar obj) { int o = __offset(22); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public Filter.UIManagerMsg.Waypoint waypoints(int j) { return waypoints(new Filter.UIManagerMsg.Waypoint(), j); }
  public Filter.UIManagerMsg.Waypoint waypoints(Filter.UIManagerMsg.Waypoint obj, int j) { int o = __offset(24); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int waypointsLength() { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; }
  public Filter.UIManagerMsg.Waypoint.Vector waypointsVector() { return waypointsVector(new Filter.UIManagerMsg.Waypoint.Vector()); }
  public Filter.UIManagerMsg.Waypoint.Vector waypointsVector(Filter.UIManagerMsg.Waypoint.Vector obj) { int o = __offset(24); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public Filter.UIManagerMsg.AISObject aisobjects(int j) { return aisobjects(new Filter.UIManagerMsg.AISObject(), j); }
  public Filter.UIManagerMsg.AISObject aisobjects(Filter.UIManagerMsg.AISObject obj, int j) { int o = __offset(26); return o != 0 ? obj.__assign(__vector(o) + j * 32, bb) : null; }
  public int aisobjectsLength() { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; }
  public Filter.UIManagerMsg.AISObject.Vector aisobjectsVector() { return aisobjectsVector(new Filter.UIManagerMsg.AISObject.Vector()); }
  public Filter.UIManagerMsg.AISObject.Vector aisobjectsVector(Filter.UIManagerMsg.AISObject.Vector obj) { int o = __offset(26); return o != 0 ? obj.__assign(__vector(o), 32, bb) : null; }

  public static void startUIManagerMsg(FlatBufferBuilder builder) { builder.startTable(12); }
  public static void addT(FlatBufferBuilder builder, long t) { builder.addLong(0, t, 0L); }
  public static void addControl(FlatBufferBuilder builder, int controlOffset) { builder.addStruct(1, controlOffset, 0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(2, positionOffset, 0); }
  public static void addVelocity(FlatBufferBuilder builder, int velocityOffset) { builder.addStruct(3, velocityOffset, 0); }
  public static void addAttitude(FlatBufferBuilder builder, int attitudeOffset) { builder.addStruct(4, attitudeOffset, 0); }
  public static void addEngine(FlatBufferBuilder builder, int engineOffset) { builder.addStruct(5, engineOffset, 0); }
  public static void addDepth(FlatBufferBuilder builder, float depth) { builder.addFloat(6, depth, 0.0f); }
  public static void addWeather(FlatBufferBuilder builder, int weatherOffset) { builder.addStruct(7, weatherOffset, 0); }
  public static void addMap(FlatBufferBuilder builder, int mapOffset) { builder.addStruct(8, mapOffset, 0); }
  public static void addRadar(FlatBufferBuilder builder, int radarOffset) { builder.addStruct(9, radarOffset, 0); }
  public static void addWaypoints(FlatBufferBuilder builder, int waypointsOffset) { builder.addOffset(10, waypointsOffset, 0); }
  public static void startWaypointsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addAisobjects(FlatBufferBuilder builder, int aisobjectsOffset) { builder.addOffset(11, aisobjectsOffset, 0); }
  public static void startAisobjectsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(32, numElems, 8); }
  public static int endUIManagerMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishUIManagerMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedUIManagerMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UIManagerMsg get(int j) { return get(new UIManagerMsg(), j); }
    public UIManagerMsg get(UIManagerMsg obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

