// automatically generated by the FlatBuffers compiler, do not modify

package Filter.UIManagerMsg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Velocity extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Velocity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float cog() { return bb.getFloat(bb_pos + 0); }
  public float sog() { return bb.getFloat(bb_pos + 4); }

  public static int createVelocity(FlatBufferBuilder builder, float cog, float sog) {
    builder.prep(4, 8);
    builder.putFloat(sog);
    builder.putFloat(cog);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Velocity get(int j) { return get(new Velocity(), j); }
    public Velocity get(Velocity obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

