package com.example.yhmtmt.aws2;// automatically generated by the FlatBuffers compiler, do not modify

public final class AutopilotMode {
  private AutopilotMode() { }
  public static final byte CURSOR = 0;
  public static final byte WP = 1;
  public static final byte WPAV = 2;
  public static final byte STAY = 3;
  public static final byte FLW_TGT = 4;
  public static final byte STB_MAN = 5;
  public static final byte NONE = 6;

  public static final String[] names = { "CURSOR", "WP", "WPAV", "STAY", "FLW_TGT", "STB_MAN", "NONE", };

  public static String name(int e) { return names[e]; }
}

