package com.example.yhmtmt.aws2;// automatically generated by the FlatBuffers compiler, do not modify

public final class ControlSource {
  private ControlSource() { }
  public static final byte UI = 0;
  public static final byte AP = 1;
  public static final byte FSET = 2;
  public static final byte NONE = 3;

  public static final String[] names = { "UI", "AP", "FSET", "NONE", };

  public static String name(int e) { return names[e]; }
}

