package com.example.yhmtmt.aws2;// automatically generated by the FlatBuffers compiler, do not modify

public final class RadarState {
  private RadarState() { }
  public static final byte OFF = 0;
  public static final byte STANDBY = 1;
  public static final byte WARMING_UP = 2;
  public static final byte TIMED_IDLE = 3;
  public static final byte STOPPING = 4;
  public static final byte SPINNING_DOWN = 5;
  public static final byte STARTING = 6;
  public static final byte SPINNING_UP = 7;
  public static final byte TRANSMIT = 8;

  public static final String[] names = { "OFF", "STANDBY", "WARMING_UP", "TIMED_IDLE", "STOPPING", "SPINNING_DOWN", "STARTING", "SPINNING_UP", "TRANSMIT", };

  public static String name(int e) { return names[e]; }
}

